app/models/asset.py
# -*- encoding: utf-8 -*-

"""
@File    :   asset.py
@Time    :   2025/07/20 22:49:33
@Author  :   test233
@Version :   1.0
"""

from ..extensions import db
from datetime import datetime


class Asset(db.Model):
    __tablename__ = "asset"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False, comment="资产名称")
    category = db.Column(db.String(50), nullable=False, comment="资产类别(服务器/网络设备/PC等)") 
    ip_address = db.Column(db.String(50), comment="IP地址")
    mac_address = db.Column(db.String(50), comment="MAC地址")
    os_version = db.Column(db.String(100), comment="操作系统版本")
    cpu_info = db.Column(db.String(100), comment="CPU信息")
    memory = db.Column(db.String(50), comment="内存容量")
    storage = db.Column(db.String(50), comment="存储容量")
    value = db.Column(db.Float, comment="资产价值")
    created_at = db.Column(db.DateTime, default=datetime.now, comment="创建时间")
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now, comment="更新时间")
    created_by = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False, comment="创建人ID")

app/routes/asset.py
# -*- encoding: utf-8 -*-

"""
@File    :   asset.py
@Time    :   2025/07/20 22:43:55
@Author  :   test233
@Version :   1.0
"""

from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from ..extensions import db
from ..forms import AssetForm,AssetSearchForm
from ..models.asset import Asset

bp = Blueprint("asset", __name__, url_prefix="/asset")


@bp.route("/")
@login_required
def list_assets():
    form = AssetSearchForm(request.args)
    
    # 处理重置操作
    if 'reset' in request.args:
        return redirect(url_for('asset.list_assets'))
    
    # 初始化查询
    query = Asset.query
    
    # 处理搜索条件
    if 'search' in request.args and form.validate():
        name = form.name.data.strip()
        query = query.filter(Asset.name.ilike(f"%{name}%"))
    
    # 处理分页参数
    page = request.args.get("page", 1, type=int)
    per_page = min(request.args.get("per_page", 10, type=int), 100)  # 限制最大值
    
    # 执行分页查询
    pagination = query.paginate(page=page, per_page=per_page)
    

    
    return render_template(
        "asset/list.html",
        pagination=pagination,
        messages=pagination.items,  # 直接使用分页对象的items
        Asset=Asset,
        title="资产列表",
        form=form,
    )


@bp.route("/create", methods=["GET", "POST"])
@login_required
def create_asset():
    form = AssetForm()
    if form.validate_on_submit():
        asset = Asset(
            name=form.name.data,
            category=form.category.data,
            value=form.value.data,
            created_by=current_user.id,
        )
        db.session.add(asset)
        db.session.commit()
        flash("Asset created successfully!", "success")
        return redirect(url_for("asset.list_assets"))
    return render_template("form.html", form=form)


@bp.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
def edit_asset(id):
    asset = Asset.query.get_or_404(id)
    if asset.created_by != current_user.id and not current_user.is_superuser:
        flash("You do not have permission to edit this asset", "danger")
        return redirect(url_for("asset.list_assets"))

    form = AssetForm(obj=asset)
    if form.validate_on_submit():
        form.populate_obj(asset)
        db.session.commit()
        flash("Asset updated successfully!", "success")
        return redirect(url_for("asset.list_assets"))
    return render_template("form.html", form=form, asset=asset)


@bp.route("/delete/<int:id>", methods=["POST"])
@login_required
def delete_asset(id):
    asset = Asset.query.get_or_404(id)
    if asset.created_by != current_user.id:
        flash("You do not have permission to delete this asset", "danger")
        return redirect(url_for("asset.list_assets"))

    db.session.delete(asset)
    db.session.commit()
    flash("Asset deleted successfully!", "success")
    return redirect(url_for("asset.list_assets"))


@bp.route("/batch_delete", methods=["POST"])
@login_required
def batch_delete():
    asset_ids = request.form.getlist("asset_ids")
    if not asset_ids:
        flash("No assets selected", "warning")
        return redirect(url_for("asset.list_assets"))

    Asset.query.filter(
        Asset.id.in_(asset_ids), Asset.created_by == current_user.id
    ).delete()
    db.session.commit()
    flash(f"{len(asset_ids)} assets deleted successfully", "success")
    return redirect(url_for("asset.list_assets"))

app/templates/asset/list.html
{% extends "base.html" %}
{% from "macro/custom_table.html" import render_custom_table %}

{% block content %}
<div class="container">
    {% if title %}
        <h2>{{ title }}</h2>
    {% endif %}
    <a href="{{ url_for('asset.create_asset') }}" class="btn btn-primary mb-3">新增</a>
    {{ render_form(form, form_type='inline',method='get',button_map={'search': 'primary', 'reset': 'secondary'},button_size='sm') }}
    {{ render_custom_table(
        data=messages,
        model=Asset,
        primary_key='id',
        custom_actions=[
            ('编辑', 'pencil-fill', ('asset.edit_asset', [('id', ':id')])),
            ('删除', 'trash-fill', ('asset.delete_asset', [('id', ':id')])),
        ],
        custom_bars=[
            ("批量删除", "slash-circle", ("asset.batch_delete", [('selected_ids', '')])),
        ],
        custom_cols = [
            { 'title': '资产ID', 'field': ':id' },
            { 'title': '资产名称', 'field': ':name' },
            { 'title': '资产类别', 'field': ':category' },
            { 'title': 'IP地址', 'field': ':ip_address' },
            { 'title': 'MAC地址', 'field': ':mac_address' },
            { 'title': '操作系统版本', 'field': ':os_version' },
            { 'title': 'CPU信息', 'field': ':cpu_info' },
            { 'title': '内存容量', 'field': ':memory' },
            { 'title': '存储容量', 'field': ':storage' },
            { 'title': '资产价值', 'field': ':value' },
            { 'title': '创建时间', 'field': ':created_at', 'hide': True },
            { 'title': '更新时间', 'field': ':updated_at', 'hide': True },
            { 'title': '创建人ID', 'field': ':created_by', 'hide': True }
        ],
        responsive_class='',
        header_classes=''
    ) }}
    {{ render_pagination(pagination) }}
</div>
{% endblock %}